export const GET_ALL_COMPANIES = "ALL_COMPANIES";
export const GET_SEARCH_COMPANIES = "SEARCH_COMPANIES";
export const GET_ALL_FILTERS = "ALL_FILTERS";
export const GET_NEARBY_COMPANIES = "NEARBY_COMPANIES";
export const GET_COMPANY_BYID = "COMPANY_BYID";
export const GET_AUTO_COMPLETE = "AUTO_COMPLETE";
